### ISSUE TITLE
Empty Results Page

### ISSUE THREAD

**Issue by badwolfbit** [CodeWritingCow/NYC-restaurant-inspection-records#60]
<img width="1440" alt="Screenshot 2019-07-24 13 43 32" src="https://user-images.githubusercontent.com/7663419/61815863-233b1200-ae19-11e9-8c2e-709ff23ec4d9.png">

Results page are no longer being rendered due to a change on the OpenNYC database

<img width="883" alt="Screen Shot 2019-07-24 at 1 37 08 PM" src="https://user-images.githubusercontent.com/7663419/61815990-6e552500-ae19-11e9-9363-6298f8fffc2c.png">

borough column is now empty

**Comment by badwolfbit** [comment]
# Suggested Fix

<img width="998" alt="Screenshot 2019-07-24 13 47 26" src="https://user-images.githubusercontent.com/7663419/61816266-018e5a80-ae1a-11e9-98dc-04aeb2d2ac3e.png">

Querying the NTA code for the different boroughs instead of borough column

[NTA documentation]
https://www1.nyc.gov/assets/planning/download/pdf/data-maps/nyc-population/census2010/ntas.pdf

**Comment by CodeWritingCow** [comment]
@omenwolf The NTA code includes these abbreviations: `QN, BK, MN, BX, SI`.

We can modify the search form to use these values instead of `Queens`, `Brooklyn`, etc. We'd then modify our server to make GET requests to the NYC API, replacing the `borough` parameter with `NTA`.

**Comment by CodeWritingCow** [comment]
Meanwhile, I Tweeted NYC IT & Telecomm about the issue. They said their Open Data team is looking into it.

<img width="601" alt="Screen Shot 2019-07-24 at 2 00 31 PM" src="https://user-images.githubusercontent.com/7751862/61816968-72824200-ae1b-11e9-9c8e-e90741cea564.png">

**Comment by badwolfbit** [comment]
@CodeWritingCow 
I would suggest querying either the borough or the NTA code to safeguard against this

**Comment by CodeWritingCow** [comment]
NYC's Open Data team has fixed the API. It now returns building number and borough for buildings. However, borough names are now capitalized instead of all uppercase. PR #61 addresses this issue.

<img width="592" alt="Screen Shot 2019-07-24 at 5 17 41 PM" src="https://user-images.githubusercontent.com/7751862/61829477-01e91e80-ae37-11e9-838f-b556be5f26ae.png">

<img width="345" alt="Screen Shot 2019-07-24 at 5 17 56 PM" src="https://user-images.githubusercontent.com/7751862/61829484-057ca580-ae37-11e9-8723-f63cb0487c34.png">
